version: '3.8'

services:
  jenkins:
    image: your-jenkins-image
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - additional_tools:/usr/local/bin/additional-tools

volumes:
  jenkins_home:
  additional_tools:
