version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

  tools:
    image: your_custom_image_with_tools
    container_name: tools
    networks:
      - jenkins_network

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
