# This is the Docker compose file that created and links the 2 containers of the 2 dockerfiles together
version: '3.8'

services:
  jenkins: 
    image: jenkins:1.1
    container_name: jenkins
    ports:
      - "8086:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_network

  tools:
    image: otherapps:1.1
    container_name: otherapps
    networks:
      - jenkins_network
    volumes:
      - jenkins_home:/var/jenkins_home
    command: tail -f /dev/null  # Keeps the container running

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
